### ISSUE TITLE
Session 08252016

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#204]
- [ ] **Aurelia-CLI**
 - [x]  Default ESNext
    - [x] `npm install && au-run`   
      - [x] run 1 **[failed and fixed](https://github.com/monterey-framework/monterey/issues/209)**
    - [ ] **NOT** `npm install && au-run`
 - [x]   Default TypeScript
    - [x] `npm install && au-run`
      - [x] run 1 **[almost successful](https://github.com/monterey-framework/monterey/issues/212)**
    - [ ] **NOT** `npm install && au-run`
 - [x]  Custom **need research**
    - [ ] `npm install && au-run`
    - [ ] **NOT** `npm install && au-run`

***

- [x] skeleton-esnext-aspnetcore **[failed](https://github.com/monterey-framework/monterey/issues/213)**

- [ ] skeleton-esnext-webpack

- [x] skeleton-esnext  **succeeded**

- [x] skeleton-typescript-aspnetcore **[failed](https://github.com/monterey-framework/monterey/issues/221)**

- [ ] skeleton-typescript-webpack

- [ ] skeleton-typescript

***

- [ ] ZIP

**Comment by JeroenVinke** [comment]
Lets call it "total fail" :smile: Today I tested all these templates and confirmed that they work now
